== Best practices for using {partner-product-short-name} on AWS
If you choose *Yes* for option *WithExample*, you can explore a sample dashboard with a predefined dataset after loggin in to the Superset console. Otherwise, you must connect to your data source (for example, Redshift, Amazon S3), customize your data, and create a dashboard from the provided visualization plugins. For more information, see the https://superset.apache.org/docs[Superset documentation^].

== Security
Apache Superset provides a granular security model through users, roles, and customized permissions. Users can associate multiple roles that comprise sets of permissions to access different Superset resources, including *Model & Action*, *Views*, *Data Sources*, and *Databases*. By creating filters assigned to a particular table, the granularity of data access is row level, which means you can specify rows that meet only certain conditions for your users. For more information, see https://superset.apache.org/docs/security[Superset Security^].
